services:
  whisper-transcribe-api:
    image: ghcr.io/bob-park/whisper-transcribe-api
    build:
      dockerfile: ./Dockerfile
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
